### ISSUE TITLE
before_save is too late to :authorize_create_or_update

### ISSUE THREAD

**Issue by hidde-jan** [togglepro/pundit-resources#23]
I'm in a situation where a resource can be edited by someone until that person 'submits' it by changing a status field. If they send a request to update the resource with the new status, the current implementation of pundit-resources does not allow them to edit the resource, since it uses the updated attributes.

Currently the `authorize_create_or_update` callback is run `before_save`, which happens after the resource gets modified. This can potentially lead to a vulnerability if an attacker is able to modify a resource in such a way that they are allowed to update the resource with the updated attributes, while they were not allowed to update the resource with the attributes as they are in the database.

Replacing the `before_save` with `before_update` and `before_create` (or possibly by `before_replace_fields`) would solve this problem.
## Example:

``` ruby
class User < ActiveRecord::Base
  # flag (bool) default: false
end

class UserPolicy
  def update?
    record.flag?
  end
end

class UserResource
  attribute :flag
end
```

A user can send `PATCH {data: {id: "1", type: "users", attributes: {"flag": true}}}` and the update will succeed.
## Possible workaround

``` ruby
class UserResource < JSONAPI::Resource
  include Pundit::Resource
  skip_callback :save, :before, :authorize_create_or_update
  before_create :authorize_create_or_update
  before_update :authorize_create_or_update
end
```

**Comment by barelyknown** [comment]
I'm not sure if that's a vulnerability. When I have a similar situation, I check that the user can both modify the resource as it was before it was changed _and_ as it will be after it is changed. That seems like the best approach to me. What do you think?

**Comment by hidde-jan** [comment]
In my opinion it's definitely a vulnerability. A user is allowed to modify a resource for which the policy says no. That's how it's currently implemented.

If you want to check before and after modifying the resource if the current_user can modify it, that's up to you as the developer, but the gem should do the expected thing by default: checking if the user can update the unmodified resource before modifying it.

**Comment by barelyknown** [comment]
I'm not sure that that's the expected behavior. For example, when you're authorizing create, you are checking whether the user can create the _modified_ resource from the context of its previous state (which is new). When you authorize update, you are checking whether the user can create the the modified resource from the context of its previous state also, but in that case the previous state is the state of the resource before the changes have been made. In other words, it seems to me that this should be the policy's responsibility, and that the the policy should be checked after the resource is changed not before (given the above).

**Comment by hidde-jan** [comment]
Another example. Suppose I have a resource that belongs to a user. A user can update the resource if it belongs to that user. Even without any other validations and checks, user A should not be able to update a key belonging to user B.

However, the current implementation allows user A to send

```
data: {relationships: {user: { user A data }}}
```

to the update resource path. The resource is then first modified (i.e. the user is set to A) and only then it is checked if the user is allowed to modify the resource. Of course, the resource now belongs to A and the policy says the current user can update the resource.

**Comment by alyssais** [comment]
Here's the problem, @hidde-jan.

Let's think about a request to update an `flag?` attribute on a `User`, like your example.

You're correct in that if you're just naively checking `user.flag?` in the policy, you have a vulnerability where a non-`flag?` user can change themself to `flag?`. However, that's a problem with your policy, and not a problem with pundit-resources. The reason for that is that there's no possible way for pundit-resources to take care of this for you. Here's why:

You propose running the callbacks earlier, before attributes are assigned. Well, what happens then?

Suppose a `flag?`ed `User` isn't allowed to change themself to not be `flag?`ed, but a `flag?`ed `User` sends a request to make this change anyway. If the callbacks are run before the attributes are assigned. You can check `user.flag?` in the policy, but you have no way of seeing that the user is going to change themself to not be `flag?`ed.

This is even worse than the current system, because at least the way it is you have access to both values — `record.flag_was` and `record.flag?`. With pundit-resources set up the way it is, this policy is at least possible to implement. With your proposed changes, it becomes totally impossible.

So, with pundit-resources we've chosen the better of two bad options. There's nothing else we can do, so it's up to you to make sure you write your policies correctly in the context of this system. Here's a pattern that I've used to make that easier:

In my `ApplicationPolicy` (the common superclass of all of my policy classes), I've defined this method:

``` ruby
def old_and_new?(attribute)
  # …
end
```

And `old_and_new?(:flag)` is analogous to `record.flag_was && record.flag`, though it's a bit more complicated than that because I've expanded it to also handle relationships changing and calling `update?` on policies for the old and new values of that relationship, which in my usage was actually required much more often. I sadly can't post the implementation, because that code doesn't belong to me, and frankly looking at it now I could have done it better anyway, so this'll have to be left as an exercise to the reader if you require this much complexity.

Now, as an open source project, we obviously want to protect our users from security vulnerabilities as much as possible. To that end, the best approach we could take would be to make users aware for the potential for vulnerabilities prominent in our documentation, possibly with example code. I'm not all that involved with this project so much any more, but I imagine @barelyknown would gladly accept a pull request in this direction.

Anyway, that must be the longest GitHub comment I ever wrote. Thanks for reaching out and for the detailed issue description. :)

**Comment by valscion** [comment]
This is actually the main core principle difference between `pundit-resources` and [`jsonapi-authorization` (JA)](https://github.com/venuu/jsonapi-authorization) in that JA checks for authorization before doing any changes.

Checking authorization before operations however brings up unique challenges, as highlighted by @alyssais above. It brings a whole new host of effort required to handle these, which we over at JA haven't yet implemented properly:
- [Authorize based on params](https://github.com/venuu/jsonapi-authorization/issues/33)
- [Authorize relationship operations before modifying resources](https://github.com/venuu/jsonapi-authorization/issues/15)

If we could have a way of pre-authorizing for the parameters and relationship changes, we could have a whitelist API that allows you to easily check for the fields-to-be-changed.

Correct me if I'm wrong, but the approach taken by `pundit-resources` seems to be a blacklist approach. The policies must be carefully crafted to check for the old attribute alongside with the new attribute for every relationship and attribute that needs to be protected, done with the help of [ActiveModel dirty tracking](http://api.rubyonrails.org/classes/ActiveModel/Dirty.html). And this, if I understood correctly, is the reason why in this issue the response seems to boil down to this:

> that's a problem with your policy, and not a problem with pundit-resources

As it stands now, `pundit-resources` really isn't in the position to handle attribute changes before they're first applied in-memory. `my_model.flag = true` runs first, and only then is authorization checked. And that decision is a core principle of this gem, which is why this issue cannot be resolved by code but rather by documentation.

JA wants to do the reverse — first check whether the change is authorized and only then continuing with the operation — but we aren't there yet and it might take a long time.

I hope this helps — let me know if I got some details wrong ☺️.

**Comment by hidde-jan** [comment]
@barelyknown, @alyssais, and @valscion thanks for your responses. Especially for your detailed response, @alyssais.

I agree that on its own, pundit-resources' behavior isn't necessarily a vulnerability. Only coupled with a naive policy would you get the behavior described above, and even then only if a user can change attributes that directly influence whether or not a user is able to modify that resource.

Of course, pundit-resources is free to choose when exactly it performs the authorization, and the current choice certainly has its merits. It might even be the better approach of the two. However, if we look at for instance examples in the pundit Readme, we see things like

``` ruby
def update
  @post = Post.find(params[:id])
  authorize @post
  if @post.update(post_params)
    redirect_to @post
  else
    render :edit
  end
end
```

and `jsonapi-authorization` works in the same way. If someone isn't familiar with the `pundit-resources` source, that person might reasonably think that `pundit-resources` would work in a similar manner. I certainly was under that impression. As @valscion suggests, describing the behavior in the Readme might be enough to let people know how to build correct policies for `pundit-resources`.

The funny thing is that `jsonapi-authorization` has already had an issue raised calling for the `pundit-resources` behavior: https://github.com/venuu/jsonapi-authorization/issues/25

**Comment by valscion** [comment]
> The funny thing is that jsonapi-authorization has already had an issue raised calling for the pundit-resources behavior: venuu/jsonapi-authorization#25

Yeah, and we closed that issue as it is a feature, not a bug 😅 . It's difficult to do authorization in the world of APIs, especially when the possible attack surface area is so large. You have to be restrictive and allow for granular permissions. We currently only have the former, and don't have a baked-in solution for new parameters. Those can still be handled by jsonapi-resources hooks, such as by defining `self.updatable_fields` method.

**Comment by barelyknown** [comment]
Thanks everyone for the good discussion. I'm going to close this issue and keep the feature as is, but I've added an issue to add clarification to the README.
